SELECT 
G3E_FID
, IPID
, NODO1_ID
, NODO2_ID
, LONGITUD
, ARRANQUE

FROM GAGUAS.GM_VSTUBERIA_LN

WHERE ESTADO IN ('OPERACION', 'PROPUESTO MODIFICAR', 'PROPUESTO RETIRAR')
AND OPERADOR IN 'EMPRESAS PUBLICAS DE MEDELLIN'
